export enum RecipeActionTypesEnum {
  CREATE_RECIPE_START,
  CREATE_RECIPE_FAIL,
  CREATE_RECIPE_SUCCESS,
  CREATE_RECIPE_END,
  FETCH_RECIPE_START,
  FETCH_RECIPE_FAIL,
  FETCH_RECIPE_SUCCESS,
  FETCH_RECIPES_LIST_START,
  FETCH_RECIPES_LIST_FAIL,
  FETCH_RECIPES_LIST_SUCCESS,
}