export const cuisineList = [
  'Ainu',
  'Albanian',
  'Argentine',
  'Andhra',
  'Anglo - Indian',
  'Arab',
  'Armenian',
  'Assyrian',
  'Awadhi',
  'Azerbaijani',
  'Balochi',
  'Belarusian',
  'Bangladeshi',
  'Bengali',
  'Berber',
  'Brazilian',
  'Buddhist',
  'Bulgarian',
  'Cajun',
  'Cantonese',
  'Caribbean',
  'Chechen',
  'Chinese cuisine',
  'Chinese Islamic',
  'Circassian',
  'Crimean Tatar',
  'Cypriot',
  'Danish',
  'English',
  'Estonian',
  'French',
  'Filipino',
  'Georgian',
  'German',
  'Goan',
  'Goan Catholic',
  'Greek',
  'Gujarati',
  'Hyderabad',
  'Indian cuisine',
  'Indian Chinese',
  'Indian Singaporean cuisine',
  'Indonesian',
  'Inuit',
  'Irish',
  'Italian - American',
  'Italian cuisine',
  'Jamaican',
  'Japanese',
  'Jewish',
  'Karnataka',
  'Kazakh',
  'Keralite',
  'Korean'
];